[!196][XAI] Fix dtype in torch.inf
# Why is the change needed?

in the `PairedMinMaxNormalizer` class, `torch.inf` is used. However, it creates the following error:

```
torch.where(tgt_padding_mask, tgt_explanation, torch.inf).view(tokens_size, -1).min(dim=1).values)
RuntimeError: expected scalar type float but found double
```

This error occurs when torch 1.11.0 version is used, but not with later versions (see also https://discuss.pytorch.org/t/i-could-not-find-inf-module-in-torch/181983/6).

# What changes does the patch introduce?

Using `torch.tensor(torch.inf)` instead of just `torch.inf` solves the error with both torch 1.11.0 and 1.13.0.

# How was this patch tested?

Manual running.